// @generated by protoc-gen-es v1.7.2 with parameter "target=ts"
// @generated from file managersplitter/genesis.proto (package managersplitter, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";
import { ManagerSplitter } from "./tx_pb.js";

/**
 * GenesisState defines the managersplitter module's genesis state.
 *
 * @generated from message managersplitter.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * @generated from field: managersplitter.Params params = 1;
   */
  params?: Params;

  /**
   * @generated from field: repeated managersplitter.ManagerSplitter managerSplitters = 2;
   */
  managerSplitters: ManagerSplitter[] = [];

  /**
   * @generated from field: string nextManagerSplitterId = 3;
   */
  nextManagerSplitterId = "";

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "managersplitter.GenesisState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "params", kind: "message", T: Params },
    { no: 2, name: "managerSplitters", kind: "message", T: ManagerSplitter, repeated: true },
    { no: 3, name: "nextManagerSplitterId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}

