// @generated by protoc-gen-es v1.7.2 with parameter "target=ts"
// @generated from file maps/balances.proto (package maps, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 *
 * The UintRange is a range of IDs from some start to some end (inclusive).
 *
 * uintRanges are one of the core types used in the BitBadgesChain module.
 * They are used for everything from token IDs to time ranges to min/max balance amounts.
 *
 * See the BitBadges documentation for more information.
 *
 * @generated from message maps.UintRange
 */
export class UintRange extends Message<UintRange> {
  /**
   * The starting value of the range (inclusive).
   *
   * @generated from field: string start = 1;
   */
  start = "";

  /**
   * The ending value of the range (inclusive).
   *
   * @generated from field: string end = 2;
   */
  end = "";

  constructor(data?: PartialMessage<UintRange>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "maps.UintRange";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "start", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "end", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UintRange {
    return new UintRange().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UintRange {
    return new UintRange().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UintRange {
    return new UintRange().fromJsonString(jsonString, options);
  }

  static equals(a: UintRange | PlainMessage<UintRange> | undefined, b: UintRange | PlainMessage<UintRange> | undefined): boolean {
    return proto3.util.equals(UintRange, a, b);
  }
}

