// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file maps/packet.proto (package maps, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message maps.MapsPacketData
 */
export class MapsPacketData extends Message<MapsPacketData> {
  /**
   * @generated from oneof maps.MapsPacketData.packet
   */
  packet: {
    /**
     * @generated from field: maps.NoData noData = 1;
     */
    value: NoData;
    case: "noData";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<MapsPacketData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "maps.MapsPacketData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "noData", kind: "message", T: NoData, oneof: "packet" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MapsPacketData {
    return new MapsPacketData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MapsPacketData {
    return new MapsPacketData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MapsPacketData {
    return new MapsPacketData().fromJsonString(jsonString, options);
  }

  static equals(a: MapsPacketData | PlainMessage<MapsPacketData> | undefined, b: MapsPacketData | PlainMessage<MapsPacketData> | undefined): boolean {
    return proto3.util.equals(MapsPacketData, a, b);
  }
}

/**
 * @generated from message maps.NoData
 */
export class NoData extends Message<NoData> {
  constructor(data?: PartialMessage<NoData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "maps.NoData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NoData {
    return new NoData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NoData {
    return new NoData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NoData {
    return new NoData().fromJsonString(jsonString, options);
  }

  static equals(a: NoData | PlainMessage<NoData> | undefined, b: NoData | PlainMessage<NoData> | undefined): boolean {
    return proto3.util.equals(NoData, a, b);
  }
}

