// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.6.1
 * source: badges/genesis.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../gogoproto/gogo";
import * as dependency_2 from "./params";
import * as dependency_3 from "./badges";
import * as dependency_4 from "./balances";
import * as pb_1 from "google-protobuf";
export namespace trevormil.bitbadgeschain.badges {
    export class GenesisState extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            params?: dependency_2.trevormil.bitbadgeschain.badges.Params;
            port_id?: string;
            badges?: dependency_3.trevormil.bitbadgeschain.badges.BitBadge[];
            balances?: dependency_4.trevormil.bitbadgeschain.badges.UserBalanceInfo[];
            balance_ids?: string[];
            nextBadgeId?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3, 4, 5], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("params" in data && data.params != undefined) {
                    this.params = data.params;
                }
                if ("port_id" in data && data.port_id != undefined) {
                    this.port_id = data.port_id;
                }
                if ("badges" in data && data.badges != undefined) {
                    this.badges = data.badges;
                }
                if ("balances" in data && data.balances != undefined) {
                    this.balances = data.balances;
                }
                if ("balance_ids" in data && data.balance_ids != undefined) {
                    this.balance_ids = data.balance_ids;
                }
                if ("nextBadgeId" in data && data.nextBadgeId != undefined) {
                    this.nextBadgeId = data.nextBadgeId;
                }
            }
        }
        get params() {
            return pb_1.Message.getWrapperField(this, dependency_2.trevormil.bitbadgeschain.badges.Params, 1) as dependency_2.trevormil.bitbadgeschain.badges.Params;
        }
        set params(value: dependency_2.trevormil.bitbadgeschain.badges.Params) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_params() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get port_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set port_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get badges() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_3.trevormil.bitbadgeschain.badges.BitBadge, 3) as dependency_3.trevormil.bitbadgeschain.badges.BitBadge[];
        }
        set badges(value: dependency_3.trevormil.bitbadgeschain.badges.BitBadge[]) {
            pb_1.Message.setRepeatedWrapperField(this, 3, value);
        }
        get balances() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_4.trevormil.bitbadgeschain.badges.UserBalanceInfo, 4) as dependency_4.trevormil.bitbadgeschain.badges.UserBalanceInfo[];
        }
        set balances(value: dependency_4.trevormil.bitbadgeschain.badges.UserBalanceInfo[]) {
            pb_1.Message.setRepeatedWrapperField(this, 4, value);
        }
        get balance_ids() {
            return pb_1.Message.getFieldWithDefault(this, 5, []) as string[];
        }
        set balance_ids(value: string[]) {
            pb_1.Message.setField(this, 5, value);
        }
        get nextBadgeId() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set nextBadgeId(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        static fromObject(data: {
            params?: ReturnType<typeof dependency_2.trevormil.bitbadgeschain.badges.Params.prototype.toObject>;
            port_id?: string;
            badges?: ReturnType<typeof dependency_3.trevormil.bitbadgeschain.badges.BitBadge.prototype.toObject>[];
            balances?: ReturnType<typeof dependency_4.trevormil.bitbadgeschain.badges.UserBalanceInfo.prototype.toObject>[];
            balance_ids?: string[];
            nextBadgeId?: number;
        }): GenesisState {
            const message = new GenesisState({});
            if (data.params != null) {
                message.params = dependency_2.trevormil.bitbadgeschain.badges.Params.fromObject(data.params);
            }
            if (data.port_id != null) {
                message.port_id = data.port_id;
            }
            if (data.badges != null) {
                message.badges = data.badges.map(item => dependency_3.trevormil.bitbadgeschain.badges.BitBadge.fromObject(item));
            }
            if (data.balances != null) {
                message.balances = data.balances.map(item => dependency_4.trevormil.bitbadgeschain.badges.UserBalanceInfo.fromObject(item));
            }
            if (data.balance_ids != null) {
                message.balance_ids = data.balance_ids;
            }
            if (data.nextBadgeId != null) {
                message.nextBadgeId = data.nextBadgeId;
            }
            return message;
        }
        toObject() {
            const data: {
                params?: ReturnType<typeof dependency_2.trevormil.bitbadgeschain.badges.Params.prototype.toObject>;
                port_id?: string;
                badges?: ReturnType<typeof dependency_3.trevormil.bitbadgeschain.badges.BitBadge.prototype.toObject>[];
                balances?: ReturnType<typeof dependency_4.trevormil.bitbadgeschain.badges.UserBalanceInfo.prototype.toObject>[];
                balance_ids?: string[];
                nextBadgeId?: number;
            } = {};
            if (this.params != null) {
                data.params = this.params.toObject();
            }
            if (this.port_id != null) {
                data.port_id = this.port_id;
            }
            if (this.badges != null) {
                data.badges = this.badges.map((item: dependency_3.trevormil.bitbadgeschain.badges.BitBadge) => item.toObject());
            }
            if (this.balances != null) {
                data.balances = this.balances.map((item: dependency_4.trevormil.bitbadgeschain.badges.UserBalanceInfo) => item.toObject());
            }
            if (this.balance_ids != null) {
                data.balance_ids = this.balance_ids;
            }
            if (this.nextBadgeId != null) {
                data.nextBadgeId = this.nextBadgeId;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_params)
                writer.writeMessage(1, this.params, () => this.params.serialize(writer));
            if (this.port_id.length)
                writer.writeString(2, this.port_id);
            if (this.badges.length)
                writer.writeRepeatedMessage(3, this.badges, (item: dependency_3.trevormil.bitbadgeschain.badges.BitBadge) => item.serialize(writer));
            if (this.balances.length)
                writer.writeRepeatedMessage(4, this.balances, (item: dependency_4.trevormil.bitbadgeschain.badges.UserBalanceInfo) => item.serialize(writer));
            if (this.balance_ids.length)
                writer.writeRepeatedString(5, this.balance_ids);
            if (this.nextBadgeId != 0)
                writer.writeUint64(6, this.nextBadgeId);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GenesisState {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GenesisState();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.params, () => message.params = dependency_2.trevormil.bitbadgeschain.badges.Params.deserialize(reader));
                        break;
                    case 2:
                        message.port_id = reader.readString();
                        break;
                    case 3:
                        reader.readMessage(message.badges, () => pb_1.Message.addToRepeatedWrapperField(message, 3, dependency_3.trevormil.bitbadgeschain.badges.BitBadge.deserialize(reader), dependency_3.trevormil.bitbadgeschain.badges.BitBadge));
                        break;
                    case 4:
                        reader.readMessage(message.balances, () => pb_1.Message.addToRepeatedWrapperField(message, 4, dependency_4.trevormil.bitbadgeschain.badges.UserBalanceInfo.deserialize(reader), dependency_4.trevormil.bitbadgeschain.badges.UserBalanceInfo));
                        break;
                    case 5:
                        pb_1.Message.addToRepeatedField(message, 5, reader.readString());
                        break;
                    case 6:
                        message.nextBadgeId = reader.readUint64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GenesisState {
            return GenesisState.deserialize(bytes);
        }
    }
}
