#!/usr/bin/env bun
/**
 * Parses every `.proto` file under `proto/` for fields tagged
 * `(gogoproto.customtype) = "..."` on a `string`-typed proto3 field and
 * emits a TypeScript module exporting two frozen sets:
 *
 *   - UINT_CUSTOMTYPE_FIELDS — fields whose chain-side amino-JSON zero
 *     value is `"0"` (Uint, Int, cosmossdk.io/math.Int, etc.).
 *   - DEC_CUSTOMTYPE_FIELDS  — fields whose chain-side amino-JSON zero
 *     value is `"0.000000000000000000"` (Dec, LegacyDec, BigDec).
 *
 * Why: bufbuild proto-es strips gogoproto annotations from generated TS,
 * so at runtime we can't tell a regular `string` field from a customtype
 * one. The chain (gogoproto's protoc plugin) reads the same annotations
 * to generate Go fields with `math.Uint` / `math.Int` / etc. types whose
 * `MarshalJSON` always emits a non-empty quoted decimal. We replay the
 * same parse on the same `.proto` sources so the SDK's amino-JSON
 * pruner can coerce `""` → `"0"` (or `"0.000…"`) for these fields and
 * match what the chain reconstructs during EIP-712 verification.
 *
 * Run as a `prebuild` step. Output committed to source control so a
 * cold install (without the script) still has correct sets.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'fs';
import { join, resolve } from 'path';

const PROTO_ROOT = resolve(__dirname, '..', 'proto');
const OUT_PATH = resolve(__dirname, '..', 'src', 'transactions', 'messages', 'customtype-fields.generated.ts');

// Customtype values that produce `"0"` for the zero value when amino-marshaled.
const UINT_LIKE = new Set([
  'Uint',
  'Int',
  'cosmossdk.io/math.Int',
  'cosmossdk.io/math.Uint',
  'github.com/cosmos/cosmos-sdk/types.Int',
  'github.com/cosmos/cosmos-sdk/types.Uint'
]);

// Customtype values that produce `"0.000000000000000000"` for the zero value.
const DEC_LIKE = new Set([
  'Dec',
  'LegacyDec',
  'cosmossdk.io/math.LegacyDec',
  'github.com/cosmos/cosmos-sdk/types.Dec',
  'github.com/bitbadges/bitbadgeschain/third_party/osmomath.BigDec'
]);

function walk(dir: string, files: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, files);
    else if (entry.endsWith('.proto')) files.push(full);
  }
  return files;
}

// Match `string fieldName = N [..., (gogoproto.customtype) = "X", ...];`
// or the multi-line variant where the annotation block spans newlines.
// Captures: fieldName, customtype value.
//
// Strict on the leading `string ` — we only care about string-typed
// scalar fields. Other types (uint64 native, bytes customtype, message
// customtype) don't hit the `""` ↔ `"0"` mismatch we're solving.
const FIELD_RE =
  /\bstring\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*\d+\s*\[([^\]]*)\]/gs;
const CUSTOMTYPE_RE = /\(gogoproto\.customtype\)\s*=\s*"([^"]+)"/;

const uintFields = new Set<string>();
const decFields = new Set<string>();
let scanned = 0;
let matched = 0;

for (const path of walk(PROTO_ROOT)) {
  scanned++;
  const src = readFileSync(path, 'utf8');
  for (const m of src.matchAll(FIELD_RE)) {
    const fieldName = m[1];
    const opts = m[2];
    const ct = CUSTOMTYPE_RE.exec(opts);
    if (!ct) continue;
    const value = ct[1];
    if (UINT_LIKE.has(value)) {
      uintFields.add(fieldName);
      matched++;
    } else if (DEC_LIKE.has(value)) {
      decFields.add(fieldName);
      matched++;
    }
  }
}

// Sort for deterministic output (stable diffs across regen).
const uintArr = [...uintFields].sort();
const decArr = [...decFields].sort();

const banner = `// AUTO-GENERATED by scripts/generate-customtype-fields.ts.
// DO NOT EDIT BY HAND — re-run \`bun run scripts/generate-customtype-fields.ts\`
// after adding or renaming \`(gogoproto.customtype)\` annotations in .proto sources.
//
// Source: every \`.proto\` file under \`proto/\` (BitBadges + Cosmos SDK +
// IBC), parsed for \`string FIELD = N [(gogoproto.customtype) = "X"]\`.
// Fields where X resolves to a Uint/Int family customtype produce \`"0"\`
// for the zero value when the chain runs MarshalAminoJSON; Dec/LegacyDec
// family produce \`"0.000000000000000000"\`. The SDK's amino-JSON pruner
// uses these sets to coerce bufbuild's \`""\` (default for unset string
// fields) to the chain-canonical zero string before computing the
// keccak that wallets sign.
//
// Without this coercion, signing typed-data containing an unset Uint/
// Int/Dec customtype field produces a hash that diverges from what the
// chain reconstructs during EIP-712 verification → "signature
// verification failed".
`;

const body = `${banner}
export const UINT_CUSTOMTYPE_FIELDS: ReadonlySet<string> = Object.freeze(new Set<string>([
${uintArr.map((n) => `  '${n}',`).join('\n')}
]));

export const DEC_CUSTOMTYPE_FIELDS: ReadonlySet<string> = Object.freeze(new Set<string>([
${decArr.map((n) => `  '${n}',`).join('\n')}
]));
`;

writeFileSync(OUT_PATH, body);
console.log(`generate-customtype-fields: scanned ${scanned} .proto files, matched ${matched} customtype fields.`);
console.log(`  UINT/INT fields: ${uintArr.length}`);
console.log(`  DEC/LegacyDec fields: ${decArr.length}`);
console.log(`  Wrote ${OUT_PATH}`);
