name: Generate and Deploy Docs

on:
  push:
    branches:
      - main # or your default branch name
    paths:
      - 'packages/bitbadgesjs-sdk/**' # Only trigger when SDK changes
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: packages/bitbadgesjs-sdk
        run: npm install

      - name: Generate documentation
        run: |
          chmod +x ./scripts/gendocs.sh
          ./scripts/gendocs.sh

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/bitbadgesjs-sdk/docs
          branch: gh-pages
          clean: true
