name: Run Tests

on:
  push:
    branches:
      - main # Adjust the branch name as needed
  pull_request:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        working-directory: packages/bitbadgejs-sdk
        run: npm run test
