// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file tokenization/permissions.proto (package tokenization, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { UintRange } from "./balances_pb.js";

/**
 *
 * CollectionPermissions defines the permissions for the collection (i.e., what the manager can and cannot do).
 *
 * There are three types of permissions for a collection: ActionPermission, TokenIdsActionPermission, and CollectionApprovalPermission.
 *
 * The permission type allows fine-grained access control for each action.
 * - ActionPermission: defines when the manager can perform an action or update a field.
 * - TokenIdsActionPermission: defines when the manager can perform an action for specific tokens
 * - CollectionApprovalPermission: defines when the manager can update the transferability of the collection and what transfers can be updated vs. locked.
 *
 * Note there are a few different times here which could get confusing:
 * - permanentlyPermitted/ForbiddenTimes - the times that a permission can be performed
 * - transferTimes - the times that a transfer occurs
 * - ownershipTimes - the times when a token is owned by a user
 *
 * The permitted/permanentlyForbiddenTimes are used to determine when a permission can be executed.
 * Once a time is set to be permitted or forbidden, it is PERMANENT and cannot be changed.
 * If a time is not set to be permitted or forbidden, it is considered NEUTRAL and can be updated but is ALLOWED by default.
 *
 * IMPORTANT: We take first-match only for the permissions. This means that if you forbid time T in array index 0 and permit time T in index 1, 
 * we will only check the first permission (forbid time T) and not the second permission (permit time T).
 *
 * @generated from message tokenization.CollectionPermissions
 */
export class CollectionPermissions extends Message<CollectionPermissions> {
  /**
   * Permissions related to deleting the collection.
   *
   * @generated from field: repeated tokenization.ActionPermission canDeleteCollection = 1;
   */
  canDeleteCollection: ActionPermission[] = [];

  /**
   * Permissions related to archiving the collection.
   *
   * @generated from field: repeated tokenization.ActionPermission canArchiveCollection = 2;
   */
  canArchiveCollection: ActionPermission[] = [];

  /**
   * Permissions related to updating standards for the collection.
   *
   * @generated from field: repeated tokenization.ActionPermission canUpdateStandards = 3;
   */
  canUpdateStandards: ActionPermission[] = [];

  /**
   * Permissions related to updating custom data for the collection.
   *
   * @generated from field: repeated tokenization.ActionPermission canUpdateCustomData = 4;
   */
  canUpdateCustomData: ActionPermission[] = [];

  /**
   * Permissions related to updating the collection's manager.
   *
   * @generated from field: repeated tokenization.ActionPermission canUpdateManager = 5;
   */
  canUpdateManager: ActionPermission[] = [];

  /**
   * Permissions related to updating the metadata of the collection.
   *
   * @generated from field: repeated tokenization.ActionPermission canUpdateCollectionMetadata = 6;
   */
  canUpdateCollectionMetadata: ActionPermission[] = [];

  /**
   * Permissions related to creating more tokens for the collection.
   *
   * @generated from field: repeated tokenization.TokenIdsActionPermission canUpdateValidTokenIds = 7;
   */
  canUpdateValidTokenIds: TokenIdsActionPermission[] = [];

  /**
   * Permissions related to updating token metadata for specific tokens.
   *
   * @generated from field: repeated tokenization.TokenIdsActionPermission canUpdateTokenMetadata = 8;
   */
  canUpdateTokenMetadata: TokenIdsActionPermission[] = [];

  /**
   * Permissions related to updating collection approvals.
   *
   * @generated from field: repeated tokenization.CollectionApprovalPermission canUpdateCollectionApprovals = 9;
   */
  canUpdateCollectionApprovals: CollectionApprovalPermission[] = [];

  /**
   * Permissions related to adding more alias paths to the collection.
   *
   * @generated from field: repeated tokenization.ActionPermission canAddMoreAliasPaths = 10;
   */
  canAddMoreAliasPaths: ActionPermission[] = [];

  /**
   * Permissions related to adding more cosmos coin wrapper paths to the collection.
   *
   * @generated from field: repeated tokenization.ActionPermission canAddMoreCosmosCoinWrapperPaths = 11;
   */
  canAddMoreCosmosCoinWrapperPaths: ActionPermission[] = [];

  constructor(data?: PartialMessage<CollectionPermissions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.CollectionPermissions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "canDeleteCollection", kind: "message", T: ActionPermission, repeated: true },
    { no: 2, name: "canArchiveCollection", kind: "message", T: ActionPermission, repeated: true },
    { no: 3, name: "canUpdateStandards", kind: "message", T: ActionPermission, repeated: true },
    { no: 4, name: "canUpdateCustomData", kind: "message", T: ActionPermission, repeated: true },
    { no: 5, name: "canUpdateManager", kind: "message", T: ActionPermission, repeated: true },
    { no: 6, name: "canUpdateCollectionMetadata", kind: "message", T: ActionPermission, repeated: true },
    { no: 7, name: "canUpdateValidTokenIds", kind: "message", T: TokenIdsActionPermission, repeated: true },
    { no: 8, name: "canUpdateTokenMetadata", kind: "message", T: TokenIdsActionPermission, repeated: true },
    { no: 9, name: "canUpdateCollectionApprovals", kind: "message", T: CollectionApprovalPermission, repeated: true },
    { no: 10, name: "canAddMoreAliasPaths", kind: "message", T: ActionPermission, repeated: true },
    { no: 11, name: "canAddMoreCosmosCoinWrapperPaths", kind: "message", T: ActionPermission, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CollectionPermissions {
    return new CollectionPermissions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CollectionPermissions {
    return new CollectionPermissions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CollectionPermissions {
    return new CollectionPermissions().fromJsonString(jsonString, options);
  }

  static equals(a: CollectionPermissions | PlainMessage<CollectionPermissions> | undefined, b: CollectionPermissions | PlainMessage<CollectionPermissions> | undefined): boolean {
    return proto3.util.equals(CollectionPermissions, a, b);
  }
}

/**
 *
 * UserPermissions defines the permissions for the user about their approvals (i.e., what the user can and cannot do).
 *
 * See CollectionPermissions for more details on the different types of permissions.
 *
 * canUpdateOutgoingApprovals and canUpdateOutgoingApprovals follow the same as the canUpdateCollectionApprovals in CollectionPermissions,
 * but certain fields are removed because they are not relevant to the user.
 *
 * @generated from message tokenization.UserPermissions
 */
export class UserPermissions extends Message<UserPermissions> {
  /**
   * Permissions related to updating the user's approved outgoing transfers.
   *
   * @generated from field: repeated tokenization.UserOutgoingApprovalPermission canUpdateOutgoingApprovals = 1;
   */
  canUpdateOutgoingApprovals: UserOutgoingApprovalPermission[] = [];

  /**
   * Permissions related to updating the user's approved incoming transfers.
   *
   * @generated from field: repeated tokenization.UserIncomingApprovalPermission canUpdateIncomingApprovals = 2;
   */
  canUpdateIncomingApprovals: UserIncomingApprovalPermission[] = [];

  /**
   * Permissions related to updating auto-approval settings for self-initiated outgoing transfers (whether they are allowed by default).
   *
   * @generated from field: repeated tokenization.ActionPermission canUpdateAutoApproveSelfInitiatedOutgoingTransfers = 3;
   */
  canUpdateAutoApproveSelfInitiatedOutgoingTransfers: ActionPermission[] = [];

  /**
   * Permissions related to updating auto-approval settings for self-initiated incoming transfers (whether they are allowed by default).
   *
   * @generated from field: repeated tokenization.ActionPermission canUpdateAutoApproveSelfInitiatedIncomingTransfers = 4;
   */
  canUpdateAutoApproveSelfInitiatedIncomingTransfers: ActionPermission[] = [];

  /**
   * Permissions related to updating auto-approval settings for all incoming transfers (whether they are allowed by default).
   *
   * @generated from field: repeated tokenization.ActionPermission canUpdateAutoApproveAllIncomingTransfers = 5;
   */
  canUpdateAutoApproveAllIncomingTransfers: ActionPermission[] = [];

  constructor(data?: PartialMessage<UserPermissions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.UserPermissions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "canUpdateOutgoingApprovals", kind: "message", T: UserOutgoingApprovalPermission, repeated: true },
    { no: 2, name: "canUpdateIncomingApprovals", kind: "message", T: UserIncomingApprovalPermission, repeated: true },
    { no: 3, name: "canUpdateAutoApproveSelfInitiatedOutgoingTransfers", kind: "message", T: ActionPermission, repeated: true },
    { no: 4, name: "canUpdateAutoApproveSelfInitiatedIncomingTransfers", kind: "message", T: ActionPermission, repeated: true },
    { no: 5, name: "canUpdateAutoApproveAllIncomingTransfers", kind: "message", T: ActionPermission, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserPermissions {
    return new UserPermissions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserPermissions {
    return new UserPermissions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserPermissions {
    return new UserPermissions().fromJsonString(jsonString, options);
  }

  static equals(a: UserPermissions | PlainMessage<UserPermissions> | undefined, b: UserPermissions | PlainMessage<UserPermissions> | undefined): boolean {
    return proto3.util.equals(UserPermissions, a, b);
  }
}

/**
 *
 * CollectionApprovalPermission defines what collection approved transfers can be updated vs. are locked.
 *
 * Each transfer is broken down to a (from, to, initiatedBy, transferTime, tokenId) tuple.
 * For a transfer to match, we need to match ALL of the fields in the combination. 
 * These are determined by the fromListId, toListId, initiatedByListId, transferTimes, tokenIds fields.
 * AddressLists are used for (from, to, initiatedBy) which are a permanent list of addresses identified by an ID (see AddressLists). 
 *
 * permanentlyPermitted/ForbiddenTimes: when can the manager execute this permission?
 *
 * Ex: Let's say we are updating the transferability for the transfer tuple ("AllWithoutMint", "AllWithoutMint", "AllWithoutMint", 10, 1000).
 * We would check to find the FIRST CollectionApprovalPermission that matches this combination.
 * If we find a match, we would check the permitted/forbidden times to see if we can execute this permission (default is ALLOWED).
 *
 * Ex: So if you wanted to freeze the transferability to enforce that token ID 1 will always be transferable, you could set
 * the combination ("AllWithoutMint", "AllWithoutMint", "AllWithoutMint", "All Transfer Times", 1) to always be forbidden.
 *
 * @generated from message tokenization.CollectionApprovalPermission
 */
export class CollectionApprovalPermission extends Message<CollectionApprovalPermission> {
  /**
   * Identifier for the sender list.
   *
   * @generated from field: string fromListId = 1;
   */
  fromListId = "";

  /**
   * Identifier for the recipient list.
   *
   * @generated from field: string toListId = 2;
   */
  toListId = "";

  /**
   * Identifier for the initiator list (who is approved?).
   *
   * @generated from field: string initiatedByListId = 3;
   */
  initiatedByListId = "";

  /**
   * Specifies the times when the transfer can occur.
   *
   * @generated from field: repeated tokenization.UintRange transferTimes = 4;
   */
  transferTimes: UintRange[] = [];

  /**
   * Specifies the token IDs involved in the transfer.
   *
   * @generated from field: repeated tokenization.UintRange tokenIds = 5;
   */
  tokenIds: UintRange[] = [];

  /**
   * Specifies the ownership times for the tokens in the transfer.
   *
   * @generated from field: repeated tokenization.UintRange ownershipTimes = 6;
   */
  ownershipTimes: UintRange[] = [];

  /**
   * Identifier for the approvalId. You can use "All" or "!approvalId" for shorthand.
   * If you use "All", this approval will match to all approvalIds.
   * If you use "!approvalId", this approval will match to all approvalIds except for approvalId.
   * If you use "approvalId", this approval will match to only the specified approvalId and fail on all others.
   *
   * @generated from field: string approvalId = 7;
   */
  approvalId = "";

  /**
   * Specifies the times when this permission is permitted. Can not overlap with permanentlyForbiddenTimes.
   *
   * @generated from field: repeated tokenization.UintRange permanentlyPermittedTimes = 8;
   */
  permanentlyPermittedTimes: UintRange[] = [];

  /**
   * Specifies the times when this permission is forbidden. Can not overlap with permanentlyPermittedTimes.
   *
   * @generated from field: repeated tokenization.UintRange permanentlyForbiddenTimes = 9;
   */
  permanentlyForbiddenTimes: UintRange[] = [];

  constructor(data?: PartialMessage<CollectionApprovalPermission>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.CollectionApprovalPermission";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "fromListId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "toListId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "initiatedByListId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "transferTimes", kind: "message", T: UintRange, repeated: true },
    { no: 5, name: "tokenIds", kind: "message", T: UintRange, repeated: true },
    { no: 6, name: "ownershipTimes", kind: "message", T: UintRange, repeated: true },
    { no: 7, name: "approvalId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "permanentlyPermittedTimes", kind: "message", T: UintRange, repeated: true },
    { no: 9, name: "permanentlyForbiddenTimes", kind: "message", T: UintRange, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CollectionApprovalPermission {
    return new CollectionApprovalPermission().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CollectionApprovalPermission {
    return new CollectionApprovalPermission().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CollectionApprovalPermission {
    return new CollectionApprovalPermission().fromJsonString(jsonString, options);
  }

  static equals(a: CollectionApprovalPermission | PlainMessage<CollectionApprovalPermission> | undefined, b: CollectionApprovalPermission | PlainMessage<CollectionApprovalPermission> | undefined): boolean {
    return proto3.util.equals(CollectionApprovalPermission, a, b);
  }
}

/**
 *
 * UserOutgoingApprovalPermission defines the permissions for updating the user's approved outgoing transfers.
 *
 * @generated from message tokenization.UserOutgoingApprovalPermission
 */
export class UserOutgoingApprovalPermission extends Message<UserOutgoingApprovalPermission> {
  /**
   * Identifier for the recipient list.
   *
   * @generated from field: string toListId = 1;
   */
  toListId = "";

  /**
   * Identifier for the initiator list (who is approved?).
   *
   * @generated from field: string initiatedByListId = 2;
   */
  initiatedByListId = "";

  /**
   * Specifies the times when the transfer can occur.
   *
   * @generated from field: repeated tokenization.UintRange transferTimes = 3;
   */
  transferTimes: UintRange[] = [];

  /**
   * Specifies the token IDs involved in the transfer.
   *
   * @generated from field: repeated tokenization.UintRange tokenIds = 4;
   */
  tokenIds: UintRange[] = [];

  /**
   * Specifies the ownership times for the tokens in the transfer.
   *
   * @generated from field: repeated tokenization.UintRange ownershipTimes = 5;
   */
  ownershipTimes: UintRange[] = [];

  /**
   * Identifier for the approvalId. You can use "All" or "!approvalId" for shorthand.
   * If you use "All", this approval will match to all approvalIds.
   * If you use "!approvalId", this approval will match to all approvalIds except for approvalId.
   * If you use "approvalId", this approval will match to only the specified approvalId and fail on all others.
   *
   * @generated from field: string approvalId = 6;
   */
  approvalId = "";

  /**
   * Specifies the times when this permission is permitted. Can not overlap with permanentlyForbiddenTimes.
   *
   * @generated from field: repeated tokenization.UintRange permanentlyPermittedTimes = 7;
   */
  permanentlyPermittedTimes: UintRange[] = [];

  /**
   * Specifies the times when this permission is forbidden. Can not overlap with permanentlyPermittedTimes.
   *
   * @generated from field: repeated tokenization.UintRange permanentlyForbiddenTimes = 8;
   */
  permanentlyForbiddenTimes: UintRange[] = [];

  constructor(data?: PartialMessage<UserOutgoingApprovalPermission>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.UserOutgoingApprovalPermission";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "toListId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "initiatedByListId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "transferTimes", kind: "message", T: UintRange, repeated: true },
    { no: 4, name: "tokenIds", kind: "message", T: UintRange, repeated: true },
    { no: 5, name: "ownershipTimes", kind: "message", T: UintRange, repeated: true },
    { no: 6, name: "approvalId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "permanentlyPermittedTimes", kind: "message", T: UintRange, repeated: true },
    { no: 8, name: "permanentlyForbiddenTimes", kind: "message", T: UintRange, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserOutgoingApprovalPermission {
    return new UserOutgoingApprovalPermission().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserOutgoingApprovalPermission {
    return new UserOutgoingApprovalPermission().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserOutgoingApprovalPermission {
    return new UserOutgoingApprovalPermission().fromJsonString(jsonString, options);
  }

  static equals(a: UserOutgoingApprovalPermission | PlainMessage<UserOutgoingApprovalPermission> | undefined, b: UserOutgoingApprovalPermission | PlainMessage<UserOutgoingApprovalPermission> | undefined): boolean {
    return proto3.util.equals(UserOutgoingApprovalPermission, a, b);
  }
}

/**
 *
 * UserIncomingApprovalPermission defines the permissions for updating the user's approved incoming transfers.
 *
 * See CollectionApprovalPermission for more details. This is equivalent without the toListId field because that is always the user.
 *
 * @generated from message tokenization.UserIncomingApprovalPermission
 */
export class UserIncomingApprovalPermission extends Message<UserIncomingApprovalPermission> {
  /**
   * Identifier for the sender list.
   *
   * @generated from field: string fromListId = 1;
   */
  fromListId = "";

  /**
   * Identifier for the initiator list (who is approved?).
   *
   * @generated from field: string initiatedByListId = 2;
   */
  initiatedByListId = "";

  /**
   * Specifies the times when the transfer can occur.
   *
   * @generated from field: repeated tokenization.UintRange transferTimes = 3;
   */
  transferTimes: UintRange[] = [];

  /**
   * Specifies the token IDs involved in the transfer.
   *
   * @generated from field: repeated tokenization.UintRange tokenIds = 4;
   */
  tokenIds: UintRange[] = [];

  /**
   * Specifies the ownership times for the tokens in the transfer.
   *
   * @generated from field: repeated tokenization.UintRange ownershipTimes = 5;
   */
  ownershipTimes: UintRange[] = [];

  /**
   * Identifier for the approvalId. You can use "All" or "!approvalId" for shorthand.
   * If you use "All", this approval will match to all approvalIds.
   * If you use "!approvalId", this approval will match to all approvalIds except for approvalId.
   * If you use "approvalId", this approval will match to only the specified approvalId and fail on all others.
   *
   * @generated from field: string approvalId = 6;
   */
  approvalId = "";

  /**
   * Specifies the times when this permission is permitted. Can not overlap with permanentlyForbiddenTimes.
   *
   * @generated from field: repeated tokenization.UintRange permanentlyPermittedTimes = 7;
   */
  permanentlyPermittedTimes: UintRange[] = [];

  /**
   * Specifies the times when this permission is forbidden. Can not overlap with permanentlyPermittedTimes.
   *
   * @generated from field: repeated tokenization.UintRange permanentlyForbiddenTimes = 8;
   */
  permanentlyForbiddenTimes: UintRange[] = [];

  constructor(data?: PartialMessage<UserIncomingApprovalPermission>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.UserIncomingApprovalPermission";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "fromListId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "initiatedByListId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "transferTimes", kind: "message", T: UintRange, repeated: true },
    { no: 4, name: "tokenIds", kind: "message", T: UintRange, repeated: true },
    { no: 5, name: "ownershipTimes", kind: "message", T: UintRange, repeated: true },
    { no: 6, name: "approvalId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "permanentlyPermittedTimes", kind: "message", T: UintRange, repeated: true },
    { no: 8, name: "permanentlyForbiddenTimes", kind: "message", T: UintRange, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserIncomingApprovalPermission {
    return new UserIncomingApprovalPermission().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserIncomingApprovalPermission {
    return new UserIncomingApprovalPermission().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserIncomingApprovalPermission {
    return new UserIncomingApprovalPermission().fromJsonString(jsonString, options);
  }

  static equals(a: UserIncomingApprovalPermission | PlainMessage<UserIncomingApprovalPermission> | undefined, b: UserIncomingApprovalPermission | PlainMessage<UserIncomingApprovalPermission> | undefined): boolean {
    return proto3.util.equals(UserIncomingApprovalPermission, a, b);
  }
}

/**
 *
 * TokenIdsActionPermission defines the permissions for performing an action for specific tokens.
 * Currently, this is only used for creating new tokens.
 *
 * Ex: If you want to lock the ability to create new tokens for tokenIds [1,2] at ownershipTimes 1/1/2020 - 1/1/2021, 
 * you could set the combination (tokenIds: [1,2], ownershipTimes: [1/1/2020 - 1/1/2021]) to always be forbidden.
 *
 * @generated from message tokenization.TokenIdsActionPermission
 */
export class TokenIdsActionPermission extends Message<TokenIdsActionPermission> {
  /**
   * Specifies the token IDs involved in the transfer.
   *
   * @generated from field: repeated tokenization.UintRange tokenIds = 1;
   */
  tokenIds: UintRange[] = [];

  /**
   * Specifies the times when this permission is permitted. Can not overlap with permanentlyForbiddenTimes.
   *
   * @generated from field: repeated tokenization.UintRange permanentlyPermittedTimes = 2;
   */
  permanentlyPermittedTimes: UintRange[] = [];

  /**
   * Specifies the times when this permission is forbidden. Can not overlap with permanentlyPermittedTimes.
   *
   * @generated from field: repeated tokenization.UintRange permanentlyForbiddenTimes = 3;
   */
  permanentlyForbiddenTimes: UintRange[] = [];

  constructor(data?: PartialMessage<TokenIdsActionPermission>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.TokenIdsActionPermission";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tokenIds", kind: "message", T: UintRange, repeated: true },
    { no: 2, name: "permanentlyPermittedTimes", kind: "message", T: UintRange, repeated: true },
    { no: 3, name: "permanentlyForbiddenTimes", kind: "message", T: UintRange, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TokenIdsActionPermission {
    return new TokenIdsActionPermission().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TokenIdsActionPermission {
    return new TokenIdsActionPermission().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TokenIdsActionPermission {
    return new TokenIdsActionPermission().fromJsonString(jsonString, options);
  }

  static equals(a: TokenIdsActionPermission | PlainMessage<TokenIdsActionPermission> | undefined, b: TokenIdsActionPermission | PlainMessage<TokenIdsActionPermission> | undefined): boolean {
    return proto3.util.equals(TokenIdsActionPermission, a, b);
  }
}

/**
 *
 * ActionPermission defines the permissions for performing an action.
 *
 * This is simple and straightforward as the only thing we need to check is the permitted/forbidden times.
 *
 * @generated from message tokenization.ActionPermission
 */
export class ActionPermission extends Message<ActionPermission> {
  /**
   * Specifies the times when this permission is permitted. Can not overlap with permanentlyForbiddenTimes.
   *
   * @generated from field: repeated tokenization.UintRange permanentlyPermittedTimes = 1;
   */
  permanentlyPermittedTimes: UintRange[] = [];

  /**
   * Specifies the times when this permission is forbidden. Can not overlap with permanentlyPermittedTimes.
   *
   * @generated from field: repeated tokenization.UintRange permanentlyForbiddenTimes = 2;
   */
  permanentlyForbiddenTimes: UintRange[] = [];

  constructor(data?: PartialMessage<ActionPermission>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.ActionPermission";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "permanentlyPermittedTimes", kind: "message", T: UintRange, repeated: true },
    { no: 2, name: "permanentlyForbiddenTimes", kind: "message", T: UintRange, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ActionPermission {
    return new ActionPermission().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ActionPermission {
    return new ActionPermission().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ActionPermission {
    return new ActionPermission().fromJsonString(jsonString, options);
  }

  static equals(a: ActionPermission | PlainMessage<ActionPermission> | undefined, b: ActionPermission | PlainMessage<ActionPermission> | undefined): boolean {
    return proto3.util.equals(ActionPermission, a, b);
  }
}

