// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file tokenization/query.proto (package tokenization, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";
import { TokenCollection } from "./collections_pb.js";
import { UserBalanceStore } from "./user_balance_store_pb.js";
import { AddressList } from "./address_lists_pb.js";
import { ApprovalTracker } from "./approval_tracking_pb.js";
import { DynamicStore, DynamicStoreValue } from "./dynamic_stores_pb.js";
import { VoteProof } from "./challenges_pb.js";

/**
 * QueryParamsRequest is request type for the Query/Params RPC method.
 *
 * @generated from message tokenization.QueryParamsRequest
 */
export class QueryParamsRequest extends Message<QueryParamsRequest> {
  constructor(data?: PartialMessage<QueryParamsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryParamsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined, b: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined): boolean {
    return proto3.util.equals(QueryParamsRequest, a, b);
  }
}

/**
 * QueryParamsResponse is response type for the Query/Params RPC method.
 *
 * @generated from message tokenization.QueryParamsResponse
 */
export class QueryParamsResponse extends Message<QueryParamsResponse> {
  /**
   * params holds all the parameters of this module.
   *
   * @generated from field: tokenization.Params params = 1;
   */
  params?: Params;

  constructor(data?: PartialMessage<QueryParamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryParamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "params", kind: "message", T: Params },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined, b: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined): boolean {
    return proto3.util.equals(QueryParamsResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetCollectionRequest
 */
export class QueryGetCollectionRequest extends Message<QueryGetCollectionRequest> {
  /**
   * @generated from field: string collectionId = 1;
   */
  collectionId = "";

  constructor(data?: PartialMessage<QueryGetCollectionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetCollectionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "collectionId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetCollectionRequest {
    return new QueryGetCollectionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetCollectionRequest {
    return new QueryGetCollectionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetCollectionRequest {
    return new QueryGetCollectionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetCollectionRequest | PlainMessage<QueryGetCollectionRequest> | undefined, b: QueryGetCollectionRequest | PlainMessage<QueryGetCollectionRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetCollectionRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetCollectionResponse
 */
export class QueryGetCollectionResponse extends Message<QueryGetCollectionResponse> {
  /**
   * @generated from field: tokenization.TokenCollection collection = 1;
   */
  collection?: TokenCollection;

  constructor(data?: PartialMessage<QueryGetCollectionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetCollectionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "collection", kind: "message", T: TokenCollection },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetCollectionResponse {
    return new QueryGetCollectionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetCollectionResponse {
    return new QueryGetCollectionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetCollectionResponse {
    return new QueryGetCollectionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetCollectionResponse | PlainMessage<QueryGetCollectionResponse> | undefined, b: QueryGetCollectionResponse | PlainMessage<QueryGetCollectionResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetCollectionResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetBalanceRequest
 */
export class QueryGetBalanceRequest extends Message<QueryGetBalanceRequest> {
  /**
   * @generated from field: string collectionId = 1;
   */
  collectionId = "";

  /**
   * @generated from field: string address = 2;
   */
  address = "";

  constructor(data?: PartialMessage<QueryGetBalanceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetBalanceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "collectionId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetBalanceRequest {
    return new QueryGetBalanceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetBalanceRequest {
    return new QueryGetBalanceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetBalanceRequest {
    return new QueryGetBalanceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetBalanceRequest | PlainMessage<QueryGetBalanceRequest> | undefined, b: QueryGetBalanceRequest | PlainMessage<QueryGetBalanceRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetBalanceRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetBalanceResponse
 */
export class QueryGetBalanceResponse extends Message<QueryGetBalanceResponse> {
  /**
   * @generated from field: tokenization.UserBalanceStore balance = 1;
   */
  balance?: UserBalanceStore;

  constructor(data?: PartialMessage<QueryGetBalanceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetBalanceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "balance", kind: "message", T: UserBalanceStore },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetBalanceResponse {
    return new QueryGetBalanceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetBalanceResponse {
    return new QueryGetBalanceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetBalanceResponse {
    return new QueryGetBalanceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetBalanceResponse | PlainMessage<QueryGetBalanceResponse> | undefined, b: QueryGetBalanceResponse | PlainMessage<QueryGetBalanceResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetBalanceResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetAddressListRequest
 */
export class QueryGetAddressListRequest extends Message<QueryGetAddressListRequest> {
  /**
   * @generated from field: string listId = 1;
   */
  listId = "";

  constructor(data?: PartialMessage<QueryGetAddressListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetAddressListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "listId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetAddressListRequest {
    return new QueryGetAddressListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetAddressListRequest {
    return new QueryGetAddressListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetAddressListRequest {
    return new QueryGetAddressListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetAddressListRequest | PlainMessage<QueryGetAddressListRequest> | undefined, b: QueryGetAddressListRequest | PlainMessage<QueryGetAddressListRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetAddressListRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetAddressListResponse
 */
export class QueryGetAddressListResponse extends Message<QueryGetAddressListResponse> {
  /**
   * @generated from field: tokenization.AddressList list = 1;
   */
  list?: AddressList;

  constructor(data?: PartialMessage<QueryGetAddressListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetAddressListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: AddressList },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetAddressListResponse {
    return new QueryGetAddressListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetAddressListResponse {
    return new QueryGetAddressListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetAddressListResponse {
    return new QueryGetAddressListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetAddressListResponse | PlainMessage<QueryGetAddressListResponse> | undefined, b: QueryGetAddressListResponse | PlainMessage<QueryGetAddressListResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetAddressListResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetApprovalTrackerRequest
 */
export class QueryGetApprovalTrackerRequest extends Message<QueryGetApprovalTrackerRequest> {
  /**
   * @generated from field: string amountTrackerId = 1;
   */
  amountTrackerId = "";

  /**
   * "collection" or "incoming" or "outgoing"
   *
   * @generated from field: string approvalLevel = 2;
   */
  approvalLevel = "";

  /**
   * if approvalLevel is "collection", leave blank
   *
   * @generated from field: string approverAddress = 3;
   */
  approverAddress = "";

  /**
   * @generated from field: string trackerType = 4;
   */
  trackerType = "";

  /**
   * @generated from field: string collectionId = 5;
   */
  collectionId = "";

  /**
   * if trackerType is "overall", leave blank
   *
   * @generated from field: string approvedAddress = 6;
   */
  approvedAddress = "";

  /**
   * @generated from field: string approvalId = 7;
   */
  approvalId = "";

  constructor(data?: PartialMessage<QueryGetApprovalTrackerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetApprovalTrackerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "amountTrackerId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "approvalLevel", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "approverAddress", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "trackerType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "collectionId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "approvedAddress", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "approvalId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetApprovalTrackerRequest {
    return new QueryGetApprovalTrackerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetApprovalTrackerRequest {
    return new QueryGetApprovalTrackerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetApprovalTrackerRequest {
    return new QueryGetApprovalTrackerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetApprovalTrackerRequest | PlainMessage<QueryGetApprovalTrackerRequest> | undefined, b: QueryGetApprovalTrackerRequest | PlainMessage<QueryGetApprovalTrackerRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetApprovalTrackerRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetApprovalTrackerResponse
 */
export class QueryGetApprovalTrackerResponse extends Message<QueryGetApprovalTrackerResponse> {
  /**
   * @generated from field: tokenization.ApprovalTracker tracker = 1;
   */
  tracker?: ApprovalTracker;

  constructor(data?: PartialMessage<QueryGetApprovalTrackerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetApprovalTrackerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tracker", kind: "message", T: ApprovalTracker },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetApprovalTrackerResponse {
    return new QueryGetApprovalTrackerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetApprovalTrackerResponse {
    return new QueryGetApprovalTrackerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetApprovalTrackerResponse {
    return new QueryGetApprovalTrackerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetApprovalTrackerResponse | PlainMessage<QueryGetApprovalTrackerResponse> | undefined, b: QueryGetApprovalTrackerResponse | PlainMessage<QueryGetApprovalTrackerResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetApprovalTrackerResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetChallengeTrackerRequest
 */
export class QueryGetChallengeTrackerRequest extends Message<QueryGetChallengeTrackerRequest> {
  /**
   * @generated from field: string collectionId = 1;
   */
  collectionId = "";

  /**
   * "collection" or "incoming" or "outgoing"
   *
   * @generated from field: string approvalLevel = 2;
   */
  approvalLevel = "";

  /**
   * if approvalLevel is "collection", leave blank
   *
   * @generated from field: string approverAddress = 3;
   */
  approverAddress = "";

  /**
   * @generated from field: string challengeTrackerId = 4;
   */
  challengeTrackerId = "";

  /**
   * @generated from field: string leafIndex = 5;
   */
  leafIndex = "";

  /**
   * @generated from field: string approvalId = 6;
   */
  approvalId = "";

  constructor(data?: PartialMessage<QueryGetChallengeTrackerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetChallengeTrackerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "collectionId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "approvalLevel", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "approverAddress", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "challengeTrackerId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "leafIndex", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "approvalId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetChallengeTrackerRequest {
    return new QueryGetChallengeTrackerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetChallengeTrackerRequest {
    return new QueryGetChallengeTrackerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetChallengeTrackerRequest {
    return new QueryGetChallengeTrackerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetChallengeTrackerRequest | PlainMessage<QueryGetChallengeTrackerRequest> | undefined, b: QueryGetChallengeTrackerRequest | PlainMessage<QueryGetChallengeTrackerRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetChallengeTrackerRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetChallengeTrackerResponse
 */
export class QueryGetChallengeTrackerResponse extends Message<QueryGetChallengeTrackerResponse> {
  /**
   * @generated from field: string numUsed = 1;
   */
  numUsed = "";

  constructor(data?: PartialMessage<QueryGetChallengeTrackerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetChallengeTrackerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "numUsed", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetChallengeTrackerResponse {
    return new QueryGetChallengeTrackerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetChallengeTrackerResponse {
    return new QueryGetChallengeTrackerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetChallengeTrackerResponse {
    return new QueryGetChallengeTrackerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetChallengeTrackerResponse | PlainMessage<QueryGetChallengeTrackerResponse> | undefined, b: QueryGetChallengeTrackerResponse | PlainMessage<QueryGetChallengeTrackerResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetChallengeTrackerResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetDynamicStoreRequest
 */
export class QueryGetDynamicStoreRequest extends Message<QueryGetDynamicStoreRequest> {
  /**
   * @generated from field: string storeId = 1;
   */
  storeId = "";

  constructor(data?: PartialMessage<QueryGetDynamicStoreRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetDynamicStoreRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "storeId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetDynamicStoreRequest {
    return new QueryGetDynamicStoreRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetDynamicStoreRequest {
    return new QueryGetDynamicStoreRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetDynamicStoreRequest {
    return new QueryGetDynamicStoreRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetDynamicStoreRequest | PlainMessage<QueryGetDynamicStoreRequest> | undefined, b: QueryGetDynamicStoreRequest | PlainMessage<QueryGetDynamicStoreRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetDynamicStoreRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetDynamicStoreResponse
 */
export class QueryGetDynamicStoreResponse extends Message<QueryGetDynamicStoreResponse> {
  /**
   * @generated from field: tokenization.DynamicStore store = 1;
   */
  store?: DynamicStore;

  constructor(data?: PartialMessage<QueryGetDynamicStoreResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetDynamicStoreResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "store", kind: "message", T: DynamicStore },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetDynamicStoreResponse {
    return new QueryGetDynamicStoreResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetDynamicStoreResponse {
    return new QueryGetDynamicStoreResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetDynamicStoreResponse {
    return new QueryGetDynamicStoreResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetDynamicStoreResponse | PlainMessage<QueryGetDynamicStoreResponse> | undefined, b: QueryGetDynamicStoreResponse | PlainMessage<QueryGetDynamicStoreResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetDynamicStoreResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetDynamicStoreValueRequest
 */
export class QueryGetDynamicStoreValueRequest extends Message<QueryGetDynamicStoreValueRequest> {
  /**
   * @generated from field: string storeId = 1;
   */
  storeId = "";

  /**
   * @generated from field: string address = 2;
   */
  address = "";

  constructor(data?: PartialMessage<QueryGetDynamicStoreValueRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetDynamicStoreValueRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "storeId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetDynamicStoreValueRequest {
    return new QueryGetDynamicStoreValueRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetDynamicStoreValueRequest {
    return new QueryGetDynamicStoreValueRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetDynamicStoreValueRequest {
    return new QueryGetDynamicStoreValueRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetDynamicStoreValueRequest | PlainMessage<QueryGetDynamicStoreValueRequest> | undefined, b: QueryGetDynamicStoreValueRequest | PlainMessage<QueryGetDynamicStoreValueRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetDynamicStoreValueRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetDynamicStoreValueResponse
 */
export class QueryGetDynamicStoreValueResponse extends Message<QueryGetDynamicStoreValueResponse> {
  /**
   * @generated from field: tokenization.DynamicStoreValue value = 1;
   */
  value?: DynamicStoreValue;

  constructor(data?: PartialMessage<QueryGetDynamicStoreValueResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetDynamicStoreValueResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "message", T: DynamicStoreValue },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetDynamicStoreValueResponse {
    return new QueryGetDynamicStoreValueResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetDynamicStoreValueResponse {
    return new QueryGetDynamicStoreValueResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetDynamicStoreValueResponse {
    return new QueryGetDynamicStoreValueResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetDynamicStoreValueResponse | PlainMessage<QueryGetDynamicStoreValueResponse> | undefined, b: QueryGetDynamicStoreValueResponse | PlainMessage<QueryGetDynamicStoreValueResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetDynamicStoreValueResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetETHSignatureTrackerRequest
 */
export class QueryGetETHSignatureTrackerRequest extends Message<QueryGetETHSignatureTrackerRequest> {
  /**
   * @generated from field: string collectionId = 1;
   */
  collectionId = "";

  /**
   * "collection" or "incoming" or "outgoing"
   *
   * @generated from field: string approvalLevel = 2;
   */
  approvalLevel = "";

  /**
   * if approvalLevel is "collection", leave blank
   *
   * @generated from field: string approverAddress = 3;
   */
  approverAddress = "";

  /**
   * @generated from field: string approvalId = 4;
   */
  approvalId = "";

  /**
   * @generated from field: string challengeTrackerId = 5;
   */
  challengeTrackerId = "";

  /**
   * @generated from field: string signature = 6;
   */
  signature = "";

  constructor(data?: PartialMessage<QueryGetETHSignatureTrackerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetETHSignatureTrackerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "collectionId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "approvalLevel", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "approverAddress", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "approvalId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "challengeTrackerId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "signature", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetETHSignatureTrackerRequest {
    return new QueryGetETHSignatureTrackerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetETHSignatureTrackerRequest {
    return new QueryGetETHSignatureTrackerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetETHSignatureTrackerRequest {
    return new QueryGetETHSignatureTrackerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetETHSignatureTrackerRequest | PlainMessage<QueryGetETHSignatureTrackerRequest> | undefined, b: QueryGetETHSignatureTrackerRequest | PlainMessage<QueryGetETHSignatureTrackerRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetETHSignatureTrackerRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetETHSignatureTrackerResponse
 */
export class QueryGetETHSignatureTrackerResponse extends Message<QueryGetETHSignatureTrackerResponse> {
  /**
   * @generated from field: string numUsed = 1;
   */
  numUsed = "";

  constructor(data?: PartialMessage<QueryGetETHSignatureTrackerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetETHSignatureTrackerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "numUsed", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetETHSignatureTrackerResponse {
    return new QueryGetETHSignatureTrackerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetETHSignatureTrackerResponse {
    return new QueryGetETHSignatureTrackerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetETHSignatureTrackerResponse {
    return new QueryGetETHSignatureTrackerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetETHSignatureTrackerResponse | PlainMessage<QueryGetETHSignatureTrackerResponse> | undefined, b: QueryGetETHSignatureTrackerResponse | PlainMessage<QueryGetETHSignatureTrackerResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetETHSignatureTrackerResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetWrappableBalancesRequest
 */
export class QueryGetWrappableBalancesRequest extends Message<QueryGetWrappableBalancesRequest> {
  /**
   * @generated from field: string denom = 1;
   */
  denom = "";

  /**
   * @generated from field: string address = 2;
   */
  address = "";

  constructor(data?: PartialMessage<QueryGetWrappableBalancesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetWrappableBalancesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetWrappableBalancesRequest {
    return new QueryGetWrappableBalancesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetWrappableBalancesRequest {
    return new QueryGetWrappableBalancesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetWrappableBalancesRequest {
    return new QueryGetWrappableBalancesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetWrappableBalancesRequest | PlainMessage<QueryGetWrappableBalancesRequest> | undefined, b: QueryGetWrappableBalancesRequest | PlainMessage<QueryGetWrappableBalancesRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetWrappableBalancesRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetWrappableBalancesResponse
 */
export class QueryGetWrappableBalancesResponse extends Message<QueryGetWrappableBalancesResponse> {
  /**
   * @generated from field: string amount = 1;
   */
  amount = "";

  constructor(data?: PartialMessage<QueryGetWrappableBalancesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetWrappableBalancesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetWrappableBalancesResponse {
    return new QueryGetWrappableBalancesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetWrappableBalancesResponse {
    return new QueryGetWrappableBalancesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetWrappableBalancesResponse {
    return new QueryGetWrappableBalancesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetWrappableBalancesResponse | PlainMessage<QueryGetWrappableBalancesResponse> | undefined, b: QueryGetWrappableBalancesResponse | PlainMessage<QueryGetWrappableBalancesResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetWrappableBalancesResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryIsAddressReservedProtocolRequest
 */
export class QueryIsAddressReservedProtocolRequest extends Message<QueryIsAddressReservedProtocolRequest> {
  /**
   * @generated from field: string address = 1;
   */
  address = "";

  constructor(data?: PartialMessage<QueryIsAddressReservedProtocolRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryIsAddressReservedProtocolRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryIsAddressReservedProtocolRequest {
    return new QueryIsAddressReservedProtocolRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryIsAddressReservedProtocolRequest {
    return new QueryIsAddressReservedProtocolRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryIsAddressReservedProtocolRequest {
    return new QueryIsAddressReservedProtocolRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryIsAddressReservedProtocolRequest | PlainMessage<QueryIsAddressReservedProtocolRequest> | undefined, b: QueryIsAddressReservedProtocolRequest | PlainMessage<QueryIsAddressReservedProtocolRequest> | undefined): boolean {
    return proto3.util.equals(QueryIsAddressReservedProtocolRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryIsAddressReservedProtocolResponse
 */
export class QueryIsAddressReservedProtocolResponse extends Message<QueryIsAddressReservedProtocolResponse> {
  /**
   * @generated from field: bool isReservedProtocol = 1;
   */
  isReservedProtocol = false;

  constructor(data?: PartialMessage<QueryIsAddressReservedProtocolResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryIsAddressReservedProtocolResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "isReservedProtocol", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryIsAddressReservedProtocolResponse {
    return new QueryIsAddressReservedProtocolResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryIsAddressReservedProtocolResponse {
    return new QueryIsAddressReservedProtocolResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryIsAddressReservedProtocolResponse {
    return new QueryIsAddressReservedProtocolResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryIsAddressReservedProtocolResponse | PlainMessage<QueryIsAddressReservedProtocolResponse> | undefined, b: QueryIsAddressReservedProtocolResponse | PlainMessage<QueryIsAddressReservedProtocolResponse> | undefined): boolean {
    return proto3.util.equals(QueryIsAddressReservedProtocolResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetAllReservedProtocolAddressesRequest
 */
export class QueryGetAllReservedProtocolAddressesRequest extends Message<QueryGetAllReservedProtocolAddressesRequest> {
  constructor(data?: PartialMessage<QueryGetAllReservedProtocolAddressesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetAllReservedProtocolAddressesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetAllReservedProtocolAddressesRequest {
    return new QueryGetAllReservedProtocolAddressesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetAllReservedProtocolAddressesRequest {
    return new QueryGetAllReservedProtocolAddressesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetAllReservedProtocolAddressesRequest {
    return new QueryGetAllReservedProtocolAddressesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetAllReservedProtocolAddressesRequest | PlainMessage<QueryGetAllReservedProtocolAddressesRequest> | undefined, b: QueryGetAllReservedProtocolAddressesRequest | PlainMessage<QueryGetAllReservedProtocolAddressesRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetAllReservedProtocolAddressesRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetAllReservedProtocolAddressesResponse
 */
export class QueryGetAllReservedProtocolAddressesResponse extends Message<QueryGetAllReservedProtocolAddressesResponse> {
  /**
   * @generated from field: repeated string addresses = 1;
   */
  addresses: string[] = [];

  constructor(data?: PartialMessage<QueryGetAllReservedProtocolAddressesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetAllReservedProtocolAddressesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetAllReservedProtocolAddressesResponse {
    return new QueryGetAllReservedProtocolAddressesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetAllReservedProtocolAddressesResponse {
    return new QueryGetAllReservedProtocolAddressesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetAllReservedProtocolAddressesResponse {
    return new QueryGetAllReservedProtocolAddressesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetAllReservedProtocolAddressesResponse | PlainMessage<QueryGetAllReservedProtocolAddressesResponse> | undefined, b: QueryGetAllReservedProtocolAddressesResponse | PlainMessage<QueryGetAllReservedProtocolAddressesResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetAllReservedProtocolAddressesResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetVoteRequest
 */
export class QueryGetVoteRequest extends Message<QueryGetVoteRequest> {
  /**
   * @generated from field: string collectionId = 1;
   */
  collectionId = "";

  /**
   * "collection" or "incoming" or "outgoing"
   *
   * @generated from field: string approvalLevel = 2;
   */
  approvalLevel = "";

  /**
   * if approvalLevel is "collection", leave blank
   *
   * @generated from field: string approverAddress = 3;
   */
  approverAddress = "";

  /**
   * @generated from field: string approvalId = 4;
   */
  approvalId = "";

  /**
   * @generated from field: string proposalId = 5;
   */
  proposalId = "";

  /**
   * @generated from field: string voterAddress = 6;
   */
  voterAddress = "";

  constructor(data?: PartialMessage<QueryGetVoteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetVoteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "collectionId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "approvalLevel", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "approverAddress", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "approvalId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "proposalId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "voterAddress", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetVoteRequest {
    return new QueryGetVoteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetVoteRequest {
    return new QueryGetVoteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetVoteRequest {
    return new QueryGetVoteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetVoteRequest | PlainMessage<QueryGetVoteRequest> | undefined, b: QueryGetVoteRequest | PlainMessage<QueryGetVoteRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetVoteRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetVoteResponse
 */
export class QueryGetVoteResponse extends Message<QueryGetVoteResponse> {
  /**
   * @generated from field: tokenization.VoteProof vote = 1;
   */
  vote?: VoteProof;

  constructor(data?: PartialMessage<QueryGetVoteResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetVoteResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "vote", kind: "message", T: VoteProof },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetVoteResponse {
    return new QueryGetVoteResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetVoteResponse {
    return new QueryGetVoteResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetVoteResponse {
    return new QueryGetVoteResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetVoteResponse | PlainMessage<QueryGetVoteResponse> | undefined, b: QueryGetVoteResponse | PlainMessage<QueryGetVoteResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetVoteResponse, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetVotesRequest
 */
export class QueryGetVotesRequest extends Message<QueryGetVotesRequest> {
  /**
   * @generated from field: string collectionId = 1;
   */
  collectionId = "";

  /**
   * "collection" or "incoming" or "outgoing"
   *
   * @generated from field: string approvalLevel = 2;
   */
  approvalLevel = "";

  /**
   * if approvalLevel is "collection", leave blank
   *
   * @generated from field: string approverAddress = 3;
   */
  approverAddress = "";

  /**
   * @generated from field: string approvalId = 4;
   */
  approvalId = "";

  /**
   * @generated from field: string proposalId = 5;
   */
  proposalId = "";

  constructor(data?: PartialMessage<QueryGetVotesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetVotesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "collectionId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "approvalLevel", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "approverAddress", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "approvalId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "proposalId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetVotesRequest {
    return new QueryGetVotesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetVotesRequest {
    return new QueryGetVotesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetVotesRequest {
    return new QueryGetVotesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetVotesRequest | PlainMessage<QueryGetVotesRequest> | undefined, b: QueryGetVotesRequest | PlainMessage<QueryGetVotesRequest> | undefined): boolean {
    return proto3.util.equals(QueryGetVotesRequest, a, b);
  }
}

/**
 * @generated from message tokenization.QueryGetVotesResponse
 */
export class QueryGetVotesResponse extends Message<QueryGetVotesResponse> {
  /**
   * @generated from field: repeated tokenization.VoteProof votes = 1;
   */
  votes: VoteProof[] = [];

  constructor(data?: PartialMessage<QueryGetVotesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tokenization.QueryGetVotesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "votes", kind: "message", T: VoteProof, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetVotesResponse {
    return new QueryGetVotesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetVotesResponse {
    return new QueryGetVotesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetVotesResponse {
    return new QueryGetVotesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryGetVotesResponse | PlainMessage<QueryGetVotesResponse> | undefined, b: QueryGetVotesResponse | PlainMessage<QueryGetVotesResponse> | undefined): boolean {
    return proto3.util.equals(QueryGetVotesResponse, a, b);
  }
}

